app:
    placeholder_image: sound-bars.svg
    email:
        address: noreply@restfully.org
        alias: RESTFully
    resources:
        user:
            model: AppBundle\Entity\User
            manager: AppBundle\Manager\UserManager

        audiobook:
            model: AppBundle\Entity\Audiobook
            manager: AppBundle\Manager\AudiobookManager
            controller: AppBundle\Controller\AudiobookController

        author:
            model: AppBundle\Entity\Author
            controller: AppBundle\Controller\AuthorController

        speaker:
            model: AppBundle\Entity\Speaker
            controller: AppBundle\Controller\SpeakerController

        genre:
            model: AppBundle\Entity\Genre
            controller: AppBundle\Controller\GenreController

        series:
            model: AppBundle\Entity\Series
            controller: AppBundle\Controller\SeriesController

        api.client:
            model: AppBundle\Entity\Api\Client
            private: true
        api.auth_code:
            model: AppBundle\Entity\Api\AuthCode
            private: true
        api.access_token:
            model: AppBundle\Entity\Api\AccessToken
            private: true
        api.refresh_token:
            model: AppBundle\Entity\Api\RefreshToken
            private: true