app_homepage:
    path:     /
    defaults: { _controller: app.controller.dashboard:indexAction }

app_dashboard:
    prefix: /dashboard
    resource: "routing/dashboard.yml"

app_audiobooks:
    prefix: /books
    resource: "routing/audiobooks.yml"

app_authors:
    prefix: /authors
    resource: "routing/authors.yml"

app_speakers:
    prefix: /speakers
    resource: "routing/speakers.yml"

app_series:
    prefix: /series
    resource: "routing/series.yml"

app_genres:
    prefix: /genres
    resource: "routing/genres.yml"

app_account:
    prefix: /account
    resource: "routing/account.yml"

app_users:
    prefix: /users
    resource: "routing/users.yml"
    defaults:
        resource: user

app_security:
    resource: "routing/security.yml"

app_oauth_authorize:
    resource: "routing/api/oauth-authorize.yml"

app_api:
    prefix: /api
    resource: "routing/api/main.yml"