app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

app_audiobooks:
    prefix: /books
    resource: "routing/audiobooks.yml"

app_account:
    prefix: /account
    resource: "routing/account.yml"

app_security:
    resource: "routing/security.yml"

app_oauth_authorize:
    resource: "routing/api/oauth-authorize.yml"

app_api:
    prefix: /api
    resource: "routing/api/main.yml"