app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

app_registration:
    prefix: /register
    resource: "routing/registration.yml"

app_security:
    resource: "routing/security.yml"

app_oauth_authorize:
    resource: "routing/api/oauth-authorize.yml"