imports:
    - { resource: "container/controllers.yml" }
    - { resource: "container/serializer.yml" }

parameters:
 #   app.model.user.class: AppBundle\Entity\User

services:
#    app.manager.user:
#        class: AppBundle\Manager\ResourceManager
#        arguments: ["@doctrine.orm.entity_manager", "%app.model.user.class%"]


#    app.example:
#        class: AppBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
