AppBundle\Entity\Attribute:
    type: entity
    table: books_attribute
    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: nature
        type: string
        length: null
        columnDefinition: null
        fieldName: nature
    discriminatorMap:
        attribute: AppBundle\Entity\Attribute
        genre: AppBundle\Entity\Genre
        series: AppBundle\Entity\Series
    repositoryClass: AppBundle\Repository\AttributeRepository
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        description:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        canonical:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
    oneToMany:
        meta:
            targetEntity: AppBundle\Entity\AttributeMeta
            cascade: {  }
            fetch: LAZY
            mappedBy: attribute
            inversedBy: null
            orphanRemoval: false
            orderBy: null
    lifecycleCallbacks: {  }
