AppBundle\Entity\AttributeMeta:
    type: entity
    table: books_attribute_meta
    id:
        name:
            type: string
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
    fields:
        value:
            type: string
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
    manyToOne:
        attribute:
            targetEntity: AppBundle\Entity\Attribute
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: meta
            joinColumns:
                attribute_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
