AppBundle\Entity\Speaker:
    type: entity
    table: books_speaker
    repositoryClass: AppBundle\Repository\PersonRepository
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        firstName:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        lastName:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        canonical:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
    manyToMany:
        books:
            targetEntity: AppBundle\Entity\Audiobook
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinTable:
                name: books_audiobook_speakers
                schema: null
                joinColumns:
                    -
                        name: speaker_id
                        unique: false
                        nullable: true
                        onDelete: CASCADE
                        columnDefinition: null
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: audiobook_id
                        unique: false
                        nullable: true
                        onDelete: CASCADE
                        columnDefinition: null
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
