services:
    app.kernel.controller.subscriber:
        class: AppBundle\EventListener\KernelControllerSubscriber
        tags:
            - { name: kernel.event_subscriber }

    app.notification.subscriber:
        class: AppBundle\EventListener\NotificationSubscriber
        arguments:
            - "@app.manager.email"
        tags:
            - { name: kernel.event_subscriber }

    app.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]
